# Generated by Django 3.1 on 2020-10-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201030_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user_ptr',
        ),
    ]
