# Generated by Django 3.1 on 2020-10-30 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_useraccount_user_ptr'),
        ('user_account', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='user_account.useraccount'),
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
