# Generated by Django 3.1 on 2020-09-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contacts',
            field=models.ManyToManyField(to='rede_social.Profile'),
        ),
    ]
