# Generated by Django 3.1 on 2020-09-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_social', '0002_auto_20200918_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contacts',
            field=models.ManyToManyField(null=True, related_name='_profile_contacts_+', to='rede_social.Profile'),
        ),
    ]
