# Generated by Django 3.1 on 2020-09-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_social', '0003_auto_20200918_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='_profile_contacts_+', to='rede_social.Profile'),
        ),
    ]
