# Generated by Django 3.1 on 2020-09-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rede_social', '0006_timeline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
