# Generated by Django 3.1 on 2020-09-19 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rede_social', '0007_delete_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rede_social.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rede_social.profile')),
            ],
        ),
    ]
