# Generated by Django 3.1 on 2020-09-19 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rede_social', '0009_auto_20200919_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('weigth', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rede_social.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rede_social.profile')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rede_social.reaction')),
            ],
        ),
    ]
