# Generated by Django 3.1 on 2020-09-19 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rede_social', '0010_postreaction_reaction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
